### ISSUE TITLE
Options list is incomplete

### ISSUE THREAD

**Issue by bitcharmer** [chriswhocodes/VMOptionsExplorer#11]
Hi,

I absolutely love using this tool and thanks so much for hosting it online. I noticed that some time ago the page changed a little (you removed Oracle Hotspot and replaced it with OpenJDK). I think around that time the options list became incomplete.
An example is GuaranteedSafepointInerval which I remember used to display just fine and now it's gone.

Maybe worth checking this out?

Thanks!

**Comment by chriswhocodes** [comment]
Hi, I think you may have mis-spelled it in your search?
I can see that switch from OpenJDK9 onwards: https://chriswhocodes.com/hotspot_options_openjdk9.html?s=GuaranteedSafepointInterval

Kind regards,
Chris

**Comment by bitcharmer** [comment]
Hi Chris, thanks for the prompt reply. Unfortunately this is not a case of a typo:

> ./java -XX:+UnlockDiagnosticVMOptions -XX:+PrintFlagsFinal -version | grep Guaranteed                                                                                                                             Fri 16 Apr 2021 13:13:59 BST
     intx GuaranteedSafepointInterval               = 1000                                {diagnostic}
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by bitcharmer** [comment]
I'm not sure if I understand the reasoning behind closing this issue right away. The details are provided in my recent response. Thanks.

**Comment by chriswhocodes** [comment]
Hi, sorry, I thought you had typed it into the site as you'd written it in your post.
I can see it on the site from JDK9+ but looking at the sources I see it was also in JDK6-JDK8 but the definition is wrapped in a macro so it is not picked up by my parser:
```
share/vm/runtime/globals.hpp:  NOT_EMBEDDED(diagnostic(intx, GuaranteedSafepointInterval, 1000,          \
share/vm/runtime/globals.hpp:  EMBEDDED_ONLY(product(intx, GuaranteedSafepointInterval, 0,               \
```
This is the only switch to be wrapped in these macros. I will come up with a solution for it.

Thanks for reporting :)

**Comment by bitcharmer** [comment]
> Hi, sorry, I thought you had typed it into the site as you'd written it in your post.
> I can see it on the site from JDK9+ but looking at the sources I see it was also in JDK6-JDK8 but the definition is wrapped in a macro so it is not picked up by my parser:
> 
> ```
> share/vm/runtime/globals.hpp:  NOT_EMBEDDED(diagnostic(intx, GuaranteedSafepointInterval, 1000,          \
> share/vm/runtime/globals.hpp:  EMBEDDED_ONLY(product(intx, GuaranteedSafepointInterval, 0,               \
> ```
> 
> This is the only switch to be wrapped in these macros. I will come up with a solution for it.
> 
> Thanks for reporting :)

Yup, I'm a dummy. Only now did I realise my original report does indeed contain a typo. Sorry!
Many thanks for doing this. You're a hero to many of us!

**Comment by chriswhocodes** [comment]
Hi, I've added support for the EMBEDDED and NOT_EMBEDDED macros in HotSpot and it's picked up quite a few switches that I'd previously missed so thanks very much for reporting!

The fix is now live and the macro is mentioned in the default value column when detected: 
![image](https://user-images.githubusercontent.com/1898314/115301956-c9848a80-a159-11eb-94b6-faaa972e8741.png)
