### ISSUE TITLE
Support search params in the URI

### ISSUE THREAD

**Issue by mattnelson** [chriswhocodes/VMOptionsExplorer#14]
I occasionally want to share an options search result and would like the ability to put search terms in the URI. Something like this, which will perform the search on load.

```
https://chriswhocodes.com/hotspot_options_openjdk17.html?search=metaspace
```

**Comment by chriswhocodes** [comment]
Hi @mattnelson you can already do this with ?s=
e.g. https://chriswhocodes.com/hotspot_options_openjdk11.html?s=UnlockDiagnosticVMOptions
:)
