### ISSUE TITLE
Documentation on how to run VMOptionsExplorer

### ISSUE THREAD

**Issue by adibakm** [chriswhocodes/VMOptionsExplorer#16]
Hello, thank you for this great library!

I'm new to the Java ecosystem and I need some help to get run this program. Currently I'm providing the arguments `Download/jdk8u282-b08/ . json` but I get the error `Bad Xusage file: Download/jdk8u282-b08/jdk10/src/hotspot/share/Xusage.txt` I've downloaded my jdk from here https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/tag/jdk8u282-b08_openj9-0.24.0. (specifically this one [OpenJDK8U-jdk_x64_mac_openj9_8u282b08_openj9-0.24.0.tar.gz](https://github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u282-b08_openj9-0.24.0/OpenJDK8U-jdk_x64_mac_openj9_8u282b08_openj9-0.24.0.tar.gz)) 

I've also tried out https://github.com/openjdk/jdk8u-dev/releases/tag/jdk8u282-ga

Upon inspection, there is no such path to the `Xusage.txt` so I was wondering how to get around this. Also what is your recommendation in terms of downloading JDK and setting up my environment so this program can run, currently I'm using a M1 Mac. I also plan on using Jacoline in the future so if I could get some advice on how to run that as well, that would be great

**Comment by chriswhocodes** [comment]
Hi @adibakm 

VMOptionsExplorer isn't really a library, it's a tool for generating a static website which can be found at https://chriswhocodes.com and also https://foojay.io/command-line-arguments/openjdk-11/?tab=alloptions

The input files to VMOptionsExplorer are the OpenJDK source code files. I wouldn't really expect or recommend people try to generate the websites themselves.

If you wanted to build your own tools using the VM switch information I would recommend you use the JSONs I've already output: https://chriswhocodes.com/json/vmoe/

Kind regards,

Chris
