### ISSUE TITLE
Where to find the source codes for JDK so that I can parse the switch files

### ISSUE THREAD

**Issue by adibakm** [chriswhocodes/VMOptionsExplorer#17]
Hello, hope you are having a good day!

I was just curious where I can go to download Microsoft, Oracle, and OpenJDK JDKs so I can run the application without the JSON files provided in the repo.I'm trying to build from scratch

Thanks!

**Comment by chriswhocodes** [comment]
Hi @adibakm if you go to https://chriswhocodes.com and click on the vendor links it will take you to the download page for each JDK.

VMOptionsExplorer uses JDK sources where available but if only a binary JDK distribution is available then I output the PrintFlagsFinal and parse that.
