### ISSUE TITLE
`-Xmx3g -Xms4g` was OK, should not have been

### ISSUE THREAD

**Issue by jeffalder** [chriswhocodes/VMOptionsExplorer#4]
The JaCoLine tool says that `-Xmx3g -Xms4g` was all green. In reality, I don't think you should ever specify a _starting_ heap greater than the _max_ heap.

**Comment by chriswhocodes** [comment]
Agreed, the rules engine will definitely cover cases like this. Thanks for trying it out and taking the time to report these issues!

**Comment by chriswhocodes** [comment]
Basic rules engine now in place with rule for Xmx >= Xms
https://github.com/chriswhocodes/VMOptionsExplorer/commit/cc9f6eaab37694f4a8c819766f64d6e3cdd952da

Thanks for reporting :)
