### ISSUE TITLE
-Xmx4x is OK, should not be (bad size unit)

### ISSUE THREAD

**Issue by jeffalder** [chriswhocodes/VMOptionsExplorer#5]
JaCoLine says that `-Xmx4x` is OK. But since the value is a size (which fact is identified properly), `4x` should be flagged in at least one of two ways:

1. "You should not use this format"
2. "the interpreted result of `-Xmx4x` is ..."

**Comment by chriswhocodes** [comment]
Thanks for the feedback! I've got a plan to build a rules engine for validating switch values and also allowed permutations. I'll leave this issue open as a reminder.

**Comment by chriswhocodes** [comment]
Put in a temporary fix for <size> value parsing. Will replace it with the rules engine in due course.
