### ISSUE TITLE
`type` filter has unrecognizable values

### ISSUE THREAD

**Issue by bmuskalla** [chriswhocodes/VMOptionsExplorer#8]
The type dropdown for filtering by type of options has multiple broken options. Looks like this affects [Hotpot].(https://chriswhocodes.com/hotspot_options_jdk11.html)

<img width="196" alt="explorer_types" src="https://user-images.githubusercontent.com/316929/82247187-43a70080-9946-11ea-9cd7-5c00a2ca86f5.png">

Seems there is some problem escaping some of the characters.
```
<select><option value="">Show All</option><option value=""></option><option value="<directories and=" "="" zip="" jar="" files="" separated="" by="" ;="">"&gt;</option><option value="<opts></opts>"></option><option value="<size></size>"></option><option value="bool">bool</option><option value="ccstr">ccstr</option><option value="ccstrlist">ccstrlist</option><option value="double">double</option><option value="int">int</option><option value="intx">intx</option><option value="size_t">size_t</option><option value="uint">uint</option><option value="uint64_t">uint64_t</option><option value="uintx">uintx</option></select>
```

P.S.: Thanks for your hard work in the jvm ecosystem and the VM Options explorer!

**Comment by chriswhocodes** [comment]
Thanks for the report @bmuskalla :) Will get that fixed!

**Comment by chriswhocodes** [comment]
Fixed in https://github.com/chriswhocodes/VMOptionsExplorer/commit/eac6f1d2887f300f34887a3061fd3597a4547698.

Thanks for reporting!
